### ISSUE TITLE
KeyError: 'OL101'

### ISSUE THREAD

**Issue by fengyuchengdu** [klebgenomics/Kaptive#29]
Traceback (most recent call last):
  File "/home/student/miniconda3/envs/kat/bin/kaptive", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/student/miniconda3/envs/kat/lib/python3.12/site-packages/kaptive/__main__.py", line 291, in main
    if (result := typing_pipeline(
                  ^^^^^^^^^^^^^^^^
  File "/home/student/miniconda3/envs/kat/lib/python3.12/site-packages/kaptive/assembly.py", line 164, in typing_pipeline
    db.loci[locus], list(a)) for locus, a in groupby(  # Group alignments by locus
    ~~~~~~~^^^^^^^
KeyError: 'OL101'

however, some genomes worked fine...

Many thanks!

**Comment by tomdstanton** [comment]
Fixed in #30
